[[MPFI]]
arch = "aarch64"
git-tree-sha1 = "4759a20eea3999805a5e6fc423aa2a45c1df0065"
os = "macos"

    [[MPFI.download]]
    sha256 = "7a673289df1e111fca9b5ea10ac50e4c0bea8fc6179d33d2cdd257a0750cfb1b"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.aarch64-apple-darwin.tar.gz"
[[MPFI]]
arch = "aarch64"
git-tree-sha1 = "7a90f838967026996f8fc5343b8fe4a902237e84"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "a1992bab9b5143babfeee7ea39c948f02ec3afbc4151596c87ed2608704a50bb"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.aarch64-linux-gnu.tar.gz"
[[MPFI]]
arch = "aarch64"
git-tree-sha1 = "0d5d63707871cf7fddfd20c459518722eb084f4c"
libc = "musl"
os = "linux"

    [[MPFI.download]]
    sha256 = "bdaaf6e3a9ab351f68cabf369f0a8e57fb4bb6ff4d43097de0b181fc04d655a0"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.aarch64-linux-musl.tar.gz"
[[MPFI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a46e80843cb1af33c49197cd65c3f70f8c8aa7b9"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "6644ed856833c1ed8571a2e4d23a5ebf0d1a94523eca032310693b7c2c2d3c06"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.armv6l-linux-gnueabihf.tar.gz"
[[MPFI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7f410b178bced717c6bc3c1a4986cd99fbcf5b3"
libc = "musl"
os = "linux"

    [[MPFI.download]]
    sha256 = "3be619681b99b4e3432e3fce0e2d82eea53c7976d0738d9f2304e43a593e01b2"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.armv6l-linux-musleabihf.tar.gz"
[[MPFI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf774883360d3ad5c0104336ccde198c0556042b"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "cc0aed9c35762a73c2b38342d71b2724020df4686102b08a04d1943dd08427de"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.armv7l-linux-gnueabihf.tar.gz"
[[MPFI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "91461897d0a8d418206aeaa8ed09fafbff4862f4"
libc = "musl"
os = "linux"

    [[MPFI.download]]
    sha256 = "6d8eccc9d2a57cdf8db02ca6c8af5c218e210dca280a61f75a4a4e2ae1b9513f"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.armv7l-linux-musleabihf.tar.gz"
[[MPFI]]
arch = "i686"
git-tree-sha1 = "ec797bc71b11127558fa22bb694c6d632a3ad8c7"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "5a89077a2708a9e95a1e0408cbcddd2401613f2935723a46e7195fa1749cba4d"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.i686-linux-gnu.tar.gz"
[[MPFI]]
arch = "i686"
git-tree-sha1 = "78cce8e6f8058d2ae42274cb7fe93cf8b21f27af"
libc = "musl"
os = "linux"

    [[MPFI.download]]
    sha256 = "687e9d7d1c1d0523f5092b131804222aa6bcd691ecda628f9105d9a330bdb4de"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.i686-linux-musl.tar.gz"
[[MPFI]]
arch = "i686"
git-tree-sha1 = "54ef9c1231f7527c68becd17a683b4c62e371fd5"
os = "windows"

    [[MPFI.download]]
    sha256 = "4b9c22c01e85b4ba2e04fb69d8d3836eafa891a040dc8b427b00bed5d0170414"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.i686-w64-mingw32.tar.gz"
[[MPFI]]
arch = "powerpc64le"
git-tree-sha1 = "d681bdfcdea5f68e194cac8b6fc1bd1350121f56"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "8102d6952e89c4c6227ec3a163596d9ec5b67a406f5c2be0342abd38acf2361c"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.powerpc64le-linux-gnu.tar.gz"
[[MPFI]]
arch = "x86_64"
git-tree-sha1 = "2cad5fbfb2ef18b53574f9733d4bada383d6cc7a"
os = "macos"

    [[MPFI.download]]
    sha256 = "b4eae77f52bcdeab62c5c57d4e91c824336c2c9d2df7b25aa4a50587ec27981a"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.x86_64-apple-darwin.tar.gz"
[[MPFI]]
arch = "x86_64"
git-tree-sha1 = "d0c634c186e78772c18b5b6326c6b96d2c034aa0"
libc = "glibc"
os = "linux"

    [[MPFI.download]]
    sha256 = "66160dbb15f508f682e6c7180b939cf4eaccf4eb3a232a45700c99f438ec7a24"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.x86_64-linux-gnu.tar.gz"
[[MPFI]]
arch = "x86_64"
git-tree-sha1 = "162704f95fffbe3ab57d65725fec353fe7bbefd3"
libc = "musl"
os = "linux"

    [[MPFI.download]]
    sha256 = "d56715740876bf7f3cc812e444e13758f591a4ad16dafcd59cbdcb75c3324886"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.x86_64-linux-musl.tar.gz"
[[MPFI]]
arch = "x86_64"
git-tree-sha1 = "d12f8969d24223f52a00f9e1525285c8c93749bd"
os = "freebsd"

    [[MPFI.download]]
    sha256 = "4d627dd1f50d1a888de2d6146e9bcfdbe73bc34e17ddb5145272fbd2de4472df"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.x86_64-unknown-freebsd.tar.gz"
[[MPFI]]
arch = "x86_64"
git-tree-sha1 = "a324a64663953eae3f5b803e137bacb77b4c02f7"
os = "windows"

    [[MPFI.download]]
    sha256 = "a875e4e6bc387ce2581f96593d150f50763354300c037df0c153404addbbf452"
    url = "https://github.com/JuliaBinaryWrappers/MPFI_jll.jl/releases/download/MPFI-v1.5.5+0/MPFI.v1.5.5.x86_64-w64-mingw32.tar.gz"
